import { ResourceManifest } from './types/resource-types';

export const GAME_RESOURCES: ResourceManifest = {
  version: '2.3.0',
  lastUpdated: new Date().toISOString(),
  resources: [
    // === PBR纹理资源 ===
    {
      id: 'texture_pbr_hull_blue',
      url: '/assets/textures/pbr/tex-hull-blue.png',
      filename: 'tex-hull-blue.png',
      size: 257000,
      md5: 'tex-hull-blue-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '蓝色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_red',
      url: '/assets/textures/pbr/tex-hull-red.png',
      filename: 'tex-hull-red.png',
      size: 257000,
      md5: 'tex-hull-red-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '红色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_green',
      url: '/assets/textures/pbr/tex-hull-green.png',
      filename: 'tex-hull-green.png',
      size: 257000,
      md5: 'tex-hull-green-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '绿色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_white',
      url: '/assets/textures/pbr/tex-hull-white.png',
      filename: 'tex-hull-white.png',
      size: 257000,
      md5: 'tex-hull-white-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '白色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_black',
      url: '/assets/textures/pbr/tex-hull-black.png',
      filename: 'tex-hull-black.png',
      size: 257000,
      md5: 'tex-hull-black-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '黑色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_purple',
      url: '/assets/textures/pbr/tex-hull-purple.png',
      filename: 'tex-hull-purple.png',
      size: 257000,
      md5: 'tex-hull-purple-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '紫色船体PBR纹理',
    },
    {
      id: 'texture_pbr_hull_orange',
      url: '/assets/textures/pbr/tex-hull-orange.png',
      filename: 'tex-hull-orange.png',
      size: 257000,
      md5: 'tex-hull-orange-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '橙色船体PBR纹理',
    },
    {
      id: 'texture_pbr_metal_chrome',
      url: '/assets/textures/pbr/tex-metal-chrome.png',
      filename: 'tex-metal-chrome.png',
      size: 257000,
      md5: 'tex-metal-chrome-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '铬金属PBR纹理',
    },
    {
      id: 'texture_pbr_metal_gold',
      url: '/assets/textures/pbr/tex-metal-gold.png',
      filename: 'tex-metal-gold.png',
      size: 257000,
      md5: 'tex-metal-gold-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '金色金属PBR纹理',
    },
    {
      id: 'texture_pbr_metal_dark',
      url: '/assets/textures/pbr/tex-metal-dark.png',
      filename: 'tex-metal-dark.png',
      size: 257000,
      md5: 'tex-metal-dark-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '深色金属PBR纹理',
    },
    {
      id: 'texture_pbr_carbon_fiber',
      url: '/assets/textures/pbr/tex-carbon-fiber.png',
      filename: 'tex-carbon-fiber.png',
      size: 257000,
      md5: 'tex-carbon-fiber-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '碳纤维PBR纹理',
    },
    {
      id: 'texture_pbr_energy_blue',
      url: '/assets/textures/pbr/tex-energy-blue.png',
      filename: 'tex-energy-blue.png',
      size: 257000,
      md5: 'tex-energy-blue-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '蓝色能量PBR纹理',
    },
    {
      id: 'texture_pbr_energy_red',
      url: '/assets/textures/pbr/tex-energy-red.png',
      filename: 'tex-energy-red.png',
      size: 257000,
      md5: 'tex-energy-red-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '红色能量PBR纹理',
    },
    {
      id: 'texture_pbr_energy_green',
      url: '/assets/textures/pbr/tex-energy-green.png',
      filename: 'tex-energy-green.png',
      size: 257000,
      md5: 'tex-energy-green-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '绿色能量PBR纹理',
    },
    {
      id: 'texture_pbr_energy_purple',
      url: '/assets/textures/pbr/tex-energy-purple.png',
      filename: 'tex-energy-purple.png',
      size: 257000,
      md5: 'tex-energy-purple-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '紫色能量PBR纹理',
    },
    {
      id: 'texture_pbr_glass_cockpit',
      url: '/assets/textures/pbr/tex-glass-cockpit.png',
      filename: 'tex-glass-cockpit.png',
      size: 257000,
      md5: 'tex-glass-cockpit-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '驾驶舱玻璃PBR纹理',
    },
    {
      id: 'texture_pbr_rock_asteroid',
      url: '/assets/textures/pbr/tex-rock-asteroid.png',
      filename: 'tex-rock-asteroid.png',
      size: 257000,
      md5: 'tex-rock-asteroid-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '小行星岩石PBR纹理',
    },
    {
      id: 'texture_pbr_space_station',
      url: '/assets/textures/pbr/tex-space-station.png',
      filename: 'tex-space-station.png',
      size: 257000,
      md5: 'tex-space-station-pbr',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '空间站PBR纹理',
    },

    // === 纹理资源 ===
    {
      id: 'texture_metal',
      url: '/assets/textures/pbr/tex-metal-chrome.png',
      filename: 'tex-metal-chrome.png',
      size: 256000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '金属纹理贴图 - 用于飞船机身',
    },
    {
      id: 'texture_carbon',
      url: '/assets/textures/carbon.jpg',
      filename: 'carbon.jpg',
      size: 128000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '碳纤维纹理贴图 - 用于机翼',
    },
    {
      id: 'texture_glass',
      url: '/assets/textures/glass.jpg',
      filename: 'glass.jpg',
      size: 64000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '玻璃纹理贴图 - 用于驾驶舱',
    },
    {
      id: 'texture_rock',
      url: '/assets/textures/rock.jpg',
      filename: 'rock.jpg',
      size: 320000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '岩石纹理贴图 - 用于陨石和环境',
    },
    {
      id: 'texture_flare',
      url: '/assets/textures/flare.png',
      filename: 'flare.png',
      size: 16000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '光晕纹理贴图 - 用于引擎火焰和粒子效果',
    },
    {
      id: 'texture_grid',
      url: '/assets/textures/grid.png',
      filename: 'grid.png',
      size: 8000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'texture',
      version: '1.0.0',
      required: false,
      description: '网格纹理贴图 - 用于UI背景',
    },
    {
      id: 'texture_earth',
      url: '/assets/textures/earth.jpg',
      filename: 'earth.jpg',
      size: 512000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d5',
      type: 'texture',
      version: '1.0.0',
      required: false,
      description: '地球纹理贴图 - 用于背景球体',
    },
    {
      id: 'texture_metal_scratched',
      url: '/assets/textures/metalScratched.jpg',
      filename: 'metalScratched.jpg',
      size: 192000,
      md5: 'b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '划痕金属纹理贴图 - 用于引擎',
    },

    // === 动态生成的纹理 ===
    {
      id: 'texture_player_ship_diffuse',
      url: 'generated:player_ship_diffuse',
      filename: 'player_ship_diffuse.png',
      size: 512000,
      md5: 'c1d2e3f4a5b6c1d2e3f4a5b6c1d2e3f4',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '玩家飞船漫反射纹理 - 蓝银配色',
    },
    {
      id: 'texture_enemy_ship_diffuse',
      url: 'generated:enemy_ship_diffuse',
      filename: 'enemy_ship_diffuse.png',
      size: 512000,
      md5: 'd2e3f4a5b6c1d2e3f4a5b6c1d2e3f4a5',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '敌飞船漫反射纹理 - 红黑配色',
    },
    {
      id: 'texture_boss_diffuse',
      url: 'generated:boss_diffuse',
      filename: 'boss_diffuse.png',
      size: 1024000,
      md5: 'e3f4a5b6c1d2e3f4a5b6c1d2e3f4a5b6',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: 'Boss飞船漫反射纹理 - 紫色金属',
    },
    {
      id: 'texture_projectile_blue',
      url: 'generated:projectile_blue',
      filename: 'projectile_blue.png',
      size: 64000,
      md5: 'f4a5b6c1d2e3f4a5b6c1d2e3f4a5b6c1',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '蓝色子弹纹理 - 能量弹',
    },
    {
      id: 'texture_projectile_red',
      url: 'generated:projectile_red',
      filename: 'projectile_red.png',
      size: 64000,
      md5: 'a5b6c1d2e3f4a5b6c1d2e3f4a5b6c1d2',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '红色子弹纹理 - 敌人子弹',
    },
    {
      id: 'texture_explosion',
      url: 'generated:explosion',
      filename: 'explosion.png',
      size: 256000,
      md5: 'b6c1d2e3f4a5b6c1d2e3f4a5b6c1d2e3',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '爆炸粒子纹理 - 火焰渐变',
    },
    {
      id: 'texture_shield',
      url: 'generated:shield',
      filename: 'shield.png',
      size: 128000,
      md5: 'c1d2e3f4a5b6c1d2e3f4a5b6c1d2e3f4',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '护盾纹理 - 能量护盾效果',
    },
    {
      id: 'texture_engine_glow',
      url: 'generated:engine_glow',
      filename: 'engine_glow.png',
      size: 128000,
      md5: 'd2e3f4a5b6c1d2e3f4a5b6c1d2e3f4a5',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '引擎发光纹理 - 推进器火焰',
    },
    {
      id: 'texture_spark',
      url: 'generated:spark',
      filename: 'spark.png',
      size: 32000,
      md5: 'e3f4a5b6c1d2e3f4a5b6c1d2e3f4a5b6',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '火花纹理 - 武器碰撞效果',
    },
    {
      id: 'texture_powerup_health',
      url: 'generated:powerup_health',
      filename: 'powerup_health.png',
      size: 64000,
      md5: 'f4a5b6c1d2e3f4a5b6c1d2e3f4a5b6c1',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '生命道具纹理 - 绿色加号',
    },
    {
      id: 'texture_powerup_shield',
      url: 'generated:powerup_shield',
      filename: 'powerup_shield.png',
      size: 64000,
      md5: 'a5b6c1d2e3f4a5b6c1d2e3f4a5b6c1d2',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '护盾道具纹理 - 蓝色盾牌',
    },
    {
      id: 'texture_powerup_speed',
      url: 'generated:powerup_speed',
      filename: 'powerup_speed.png',
      size: 64000,
      md5: 'b6c1d2e3f4a5b6c1d2e3f4a5b6c1d2e3',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '速度道具纹理 - 黄色闪电',
    },
    {
      id: 'texture_powerup_weapon',
      url: 'generated:powerup_weapon',
      filename: 'powerup_weapon.png',
      size: 64000,
      md5: 'c1d2e3f4a5b6c1d2e3f4a5b6c1d2e3f4',
      type: 'texture',
      version: '1.0.0',
      required: true,
      description: '武器道具纹理 - 红色五角星',
    },

    // === 玩家飞船模型 ===
    {
      id: 'model_ship_fighter',
      url: '/assets/models/ships/ship-fighter.glb',
      filename: 'ship-fighter.glb',
      size: 2000000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '轻型战斗机 - 高机动性',
    },
    {
      id: 'model_ship_bomber',
      url: '/assets/models/ships/ship-bomber.glb',
      filename: 'ship-bomber.glb',
      size: 4000000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '重型轰炸机 - 高火力',
    },
    {
      id: 'model_ship_cruiser',
      url: '/assets/models/ships/ship-cruiser.glb',
      filename: 'ship-cruiser.glb',
      size: 6000000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '突击巡洋舰 - 均衡型',
    },
    {
      id: 'model_ship_stealth',
      url: '/assets/models/ships/ship-stealth.glb',
      filename: 'ship-stealth.glb',
      size: 3000000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '隐形战机 - 可隐身',
    },
    {
      id: 'model_ship_corvette',
      url: '/assets/models/ships/ship-corvette.glb',
      filename: 'ship-corvette.glb',
      size: 2500000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '快速护卫舰 - 侦察型',
    },
    {
      id: 'model_ship_dreadnought',
      url: '/assets/models/ships/ship-dreadnought.glb',
      filename: 'ship-dreadnought.glb',
      size: 10000000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '超级无畏舰 - 传奇级',
    },

    // === 敌方飞船模型 ===
    {
      id: 'model_enemy_scout',
      url: '/assets/models/enemies/enemy-scout.glb',
      filename: 'enemy-scout.glb',
      size: 800000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '侦察无人机 - 小型快速',
    },
    {
      id: 'model_enemy_fighter',
      url: '/assets/models/enemies/enemy-fighter.glb',
      filename: 'enemy-fighter.glb',
      size: 1500000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '敌方战斗机 - 标准战斗单位',
    },
    {
      id: 'model_enemy_bomber',
      url: '/assets/models/enemies/enemy-bomber.glb',
      filename: 'enemy-bomber.glb',
      size: 2000000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '轰炸无人机 - 携带炸弹',
    },
    {
      id: 'model_enemy_tank',
      url: '/assets/models/enemies/enemy-tank.glb',
      filename: 'enemy-tank.glb',
      size: 2500000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '装甲坦克 - 高防御',
    },
    {
      id: 'model_enemy_assassin',
      url: '/assets/models/enemies/enemy-assassin.glb',
      filename: 'enemy-assassin.glb',
      size: 1800000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '刺客飞船 - 精英单位',
    },
    {
      id: 'model_enemy_drone',
      url: '/assets/models/enemies/enemy-drone.glb',
      filename: 'enemy-drone.glb',
      size: 500000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '蜂群无人机 - 群体攻击',
    },
    {
      id: 'model_enemy_corvette',
      url: '/assets/models/enemies/enemy-corvette.glb',
      filename: 'enemy-corvette.glb',
      size: 2200000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '敌方护卫舰 - 支援单位',
    },
    {
      id: 'model_enemy_destroyer',
      url: '/assets/models/enemies/enemy-destroyer.glb',
      filename: 'enemy-destroyer.glb',
      size: 4000000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '驱逐舰 - 重型战舰',
    },

    // === Boss模型 ===
    {
      id: 'model_boss_sentinel',
      url: '/assets/models/bosses/boss-sentinel.glb',
      filename: 'boss-sentinel.glb',
      size: 15000000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '哨兵首领 - 第一关Boss',
    },
    {
      id: 'model_boss_overlord',
      url: '/assets/models/bosses/boss-overlord.glb',
      filename: 'boss-overlord.glb',
      size: 25000000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '霸主 - 最终Boss',
    },
    {
      id: 'model_boss_collector',
      url: '/assets/models/bosses/boss-collector.glb',
      filename: 'boss-collector.glb',
      size: 18000000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '收集者 - 中期Boss',
    },
    {
      id: 'model_boss_tyrant',
      url: '/assets/models/bosses/boss-tyrant.glb',
      filename: 'boss-tyrant.glb',
      size: 22000000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '暴君 - 倒数第二关Boss',
    },

    // === 环境结构模型 ===
    {
      id: 'model_structure_space_station',
      url: '/assets/models/structures/structure-space-station.glb',
      filename: 'structure-space-station.glb',
      size: 8000000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '空间站 - 友方设施',
    },
    {
      id: 'model_structure_asteroid_small',
      url: '/assets/models/structures/structure-asteroid-small.glb',
      filename: 'structure-asteroid-small.glb',
      size: 1000000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '小型小行星 - 障碍物',
    },
    {
      id: 'model_structure_asteroid_large',
      url: '/assets/models/structures/structure-asteroid-large.glb',
      filename: 'structure-asteroid-large.glb',
      size: 2500000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '大型小行星 - 可开采',
    },
    {
      id: 'model_structure_debris',
      url: '/assets/models/structures/structure-debris.glb',
      filename: 'structure-debris.glb',
      size: 1500000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '残骸场 - 战场遗留物',
    },
    {
      id: 'model_structure_satellite',
      url: '/assets/models/structures/structure-satellite.glb',
      filename: 'structure-satellite.glb',
      size: 600000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '通讯卫星 - 中立设施',
    },
    {
      id: 'model_structure_mining_rig',
      url: '/assets/models/structures/structure-mining-rig.glb',
      filename: 'structure-mining-rig.glb',
      size: 4000000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '采矿平台 - 资源设施',
    },
    {
      id: 'model_structure_defense_platform',
      url: '/assets/models/structures/structure-defense-platform.glb',
      filename: 'structure-defense-platform.glb',
      size: 3500000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '防御平台 - 防御设施',
    },
    {
      id: 'model_structure_planet',
      url: '/assets/models/structures/structure-planet.glb',
      filename: 'structure-planet.glb',
      size: 6000000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '行星 - 背景装饰',
    },
    {
      id: 'model_structure_moon',
      url: '/assets/models/structures/structure-moon.glb',
      filename: 'structure-moon.glb',
      size: 2000000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '卫星 - 背景装饰',
    },
    {
      id: 'model_structure_nebula',
      url: '/assets/models/structures/structure-nebula.glb',
      filename: 'structure-nebula.glb',
      size: 3000000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '星云云团 - 背景装饰',
    },

    // === 投射物模型 ===
    {
      id: 'model_projectile_laser',
      url: '/assets/models/projectiles/projectile-laser.glb',
      filename: 'projectile-laser.glb',
      size: 100000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '激光弹 - 快速直射',
    },
    {
      id: 'model_projectile_missile',
      url: '/assets/models/projectiles/projectile-missile.glb',
      filename: 'projectile-missile.glb',
      size: 300000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: true,
      description: '导弹 - 追踪目标',
    },
    {
      id: 'model_projectile_plasma',
      url: '/assets/models/projectiles/projectile-plasma.glb',
      filename: 'projectile-plasma.glb',
      size: 150000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '等离子球 - 范围伤害',
    },
    {
      id: 'model_projectile_bomb',
      url: '/assets/models/projectiles/projectile-bomb.glb',
      filename: 'projectile-bomb.glb',
      size: 400000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '集束炸弹 - 分裂攻击',
    },
    {
      id: 'model_projectile_sniper',
      url: '/assets/models/projectiles/projectile-sniper.glb',
      filename: 'projectile-sniper.glb',
      size: 80000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '狙击弹 - 高精度',
    },
    {
      id: 'model_projectile_shotgun',
      url: '/assets/models/projectiles/projectile-shotgun.glb',
      filename: 'projectile-shotgun.glb',
      size: 200000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '霰弹 - 散射攻击',
    },
    {
      id: 'model_projectile_nuke',
      url: '/assets/models/projectiles/projectile-nuke.glb',
      filename: 'projectile-nuke.glb',
      size: 600000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '核弹 - 终极武器',
    },
    {
      id: 'model_projectile_blackhole',
      url: '/assets/models/projectiles/projectile-blackhole.glb',
      filename: 'projectile-blackhole.glb',
      size: 500000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '黑洞 - 引力武器',
    },
    {
      id: 'model_projectile_gravity',
      url: '/assets/models/projectiles/projectile-gravity.glb',
      filename: 'projectile-gravity.glb',
      size: 250000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '引力井 - 吸引目标',
    },

    // === 特效模型 ===
    {
      id: 'model_effect_explosion',
      url: '/assets/models/effects/effect-explosion.glb',
      filename: 'effect-explosion.glb',
      size: 300000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '爆炸特效',
    },
    {
      id: 'model_effect_shield',
      url: '/assets/models/effects/effect-shield.glb',
      filename: 'effect-shield.glb',
      size: 200000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '护盾特效',
    },
    {
      id: 'model_effect_heal',
      url: '/assets/models/effects/effect-heal.glb',
      filename: 'effect-heal.glb',
      size: 150000,
      md5: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '治疗特效',
    },
    {
      id: 'model_effect_powerup',
      url: '/assets/models/effects/effect-powerup.glb',
      filename: 'effect-powerup.glb',
      size: 100000,
      md5: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '道具特效',
    },
    {
      id: 'model_effect_trail',
      url: '/assets/models/effects/effect-trail.glb',
      filename: 'effect-trail.glb',
      size: 80000,
      md5: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '尾迹特效',
    },
    {
      id: 'model_effect_damage',
      url: '/assets/models/effects/effect-damage.glb',
      filename: 'effect-damage.glb',
      size: 120000,
      md5: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '伤害特效',
    },
    {
      id: 'model_effect_victory',
      url: '/assets/models/effects/effect-victory.glb',
      filename: 'effect-victory.glb',
      size: 400000,
      md5: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '胜利特效',
    },
    {
      id: 'model_effect_death',
      url: '/assets/models/effects/effect-death.glb',
      filename: 'effect-death.glb',
      size: 350000,
      md5: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
      type: 'model',
      version: '1.0.0',
      required: false,
      description: '死亡特效',
    },

    // === 音频资源 ===
    {
      id: 'audio_explosion',
      url: 'generated:explosion',
      filename: 'explosion.wav',
      size: 48000,
      md5: 'f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '爆炸音效 - 飞船爆炸',
    },
    {
      id: 'audio_fire_weapon',
      url: 'generated:fire_weapon',
      filename: 'fire_weapon.wav',
      size: 32000,
      md5: 'a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '武器开火音效 - 激光射击',
    },
    {
      id: 'audio_missile_launch',
      url: 'generated:missile_launch',
      filename: 'missile_launch.wav',
      size: 64000,
      md5: 'b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '导弹发射音效',
    },
    {
      id: 'audio_hit',
      url: 'generated:hit',
      filename: 'hit.wav',
      size: 24000,
      md5: 'c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '命中音效 - 碰撞反馈',
    },
    {
      id: 'audio_powerup',
      url: 'generated:powerup',
      filename: 'powerup.wav',
      size: 32000,
      md5: 'd3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '道具获取音效',
    },
    {
      id: 'audio_engine_loop',
      url: 'generated:engine_loop',
      filename: 'engine_loop.wav',
      size: 128000,
      md5: 'e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '引擎循环音效 - 飞船引擎声',
    },
    {
      id: 'audio_bg_music_1',
      url: 'generated:bg_music_1',
      filename: 'bg_music_1.mp3',
      size: 2560000,
      md5: 'f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '背景音乐1 - 战斗风格',
    },
    {
      id: 'audio_bg_music_2',
      url: 'generated:bg_music_2',
      filename: 'bg_music_2.mp3',
      size: 2560000,
      md5: 'a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3',
      type: 'audio',
      version: '1.0.0',
      required: false,
      description: '背景音乐2 - Boss战',
    },

    // === 数据资源 ===
    {
      id: 'data_levels',
      url: 'generated:levels',
      filename: 'levels.json',
      size: 32000,
      md5: 'b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4',
      type: 'data',
      version: '1.0.0',
      required: true,
      description: '关卡配置数据',
    },
    {
      id: 'data_enemies',
      url: 'generated:enemies',
      filename: 'enemies.json',
      size: 48000,
      md5: 'c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5',
      type: 'data',
      version: '1.0.0',
      required: true,
      description: '敌人配置数据',
    },
    {
      id: 'data_powerups',
      url: 'generated:powerups',
      filename: 'powerups.json',
      size: 16000,
      md5: 'd3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6',
      type: 'data',
      version: '1.0.0',
      required: true,
      description: '道具配置数据',
    },
  ],
};

// 获取所有必需资源
export const getRequiredResources = () => {
  return GAME_RESOURCES.resources.filter((r) => r.required);
};

// 获取可选资源
export const getOptionalResources = () => {
  return GAME_RESOURCES.resources.filter((r) => !r.required);
};

// 获取按类型分组的资源
export const getResourcesByType = (type: string) => {
  return GAME_RESOURCES.resources.filter((r) => r.type === type);
};

// 获取资源统计
export const getResourceStats = () => {
  const textures = GAME_RESOURCES.resources.filter((r) => r.type === 'texture');
  const models = GAME_RESOURCES.resources.filter((r) => r.type === 'model');
  const audio = GAME_RESOURCES.resources.filter((r) => r.type === 'audio');
  const data = GAME_RESOURCES.resources.filter((r) => r.type === 'data');

  return {
    total: GAME_RESOURCES.resources.length,
    required: GAME_RESOURCES.resources.filter((r) => r.required).length,
    optional: GAME_RESOURCES.resources.filter((r) => !r.required).length,
    textures: {
      count: textures.length,
      size: textures.reduce((acc, r) => acc + r.size, 0),
    },
    models: {
      count: models.length,
      size: models.reduce((acc, r) => acc + r.size, 0),
    },
    audio: {
      count: audio.length,
      size: audio.reduce((acc, r) => acc + r.size, 0),
    },
    data: {
      count: data.length,
      size: data.reduce((acc, r) => acc + r.size, 0),
    },
    totalSize: GAME_RESOURCES.resources.reduce((acc, r) => acc + r.size, 0),
  };
};
